task: detection

evaluator:
  type: AitodCocoEvaluator
  iou_types: ['bbox', ]

num_classes: 9 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: "~/Data/shijli/datasets/AEA/images/train"
    ann_file: "~/Data/shijli/datasets/AEA/annotations/train_coco.json"
    return_masks: False
    repeat: 1   # tiny set: loop each image 10x/epoch -> 10x gradient steps/epoch (tune me)
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: "~/Data/shijli/datasets/AEA/images/val"
    ann_file: "~/Data/shijli/datasets/AEA/annotations/val_coco.json"
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
